// auto generated by go tool dist
// goos=linux goarch=amd64

#include "runtime.h"
void
runtime·GOMAXPROCS(intgo n, intgo ret)
{
#line 8 "/tmp/makerelease886106415/go/src/pkg/runtime/runtime1.goc"

	ret = runtime·gomaxprocsfunc(n);
	FLUSH(&ret);
}
void
runtime·NumCPU(intgo ret)
{
#line 12 "/tmp/makerelease886106415/go/src/pkg/runtime/runtime1.goc"

	ret = runtime·ncpu;
	FLUSH(&ret);
}
