#!/bin/sh

if [ -z "$SLIRP_PORTS" ]
then
    exec slirp-fullbolt "$@"
else
    tmp=$(mktemp /tmp/slirp.XXXX)

    echo 'exec slirp-fullbolt "host addr $HOST_IP" \\' > $tmp
    for i in $SLIRP_PORTS
    do
        echo '"redir '$i' 10.1.1.1:'$i'"' \\ >> $tmp
    done

    echo '"$@"' >> $tmp

    exec /bin/sh $tmp "$@"
fi
