image:
  file: .gitpod.Dockerfile
tasks:
  - command: kotlinc main.kt && kotlin MainKt
vscode:
  extensions:
    - mathiasfrohlich.Kotlin@1.7.0:9xQZtwTUg4bdXHCMyxM7vQ==
    - fwcd.kotlin@0.2.11:moh8IDanzsIlhtK2IeiLmQ==
